//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     GenAPI Version: 5.0.2.37403
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Fluxonaut.Browser.Core
{
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class BrowserSettings : Fluxonaut.Browser.IBrowserSettings
    {
        public BrowserSettings() { }
        public BrowserSettings(bool autoDispose) { }
        public virtual string AcceptLanguageList { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState ApplicationCache { get { throw null; } set { } }
        public virtual bool AutoDispose { get { throw null; } }
        public virtual uint BackgroundColor { get { throw null; } set { } }
        public virtual string CursiveFontFamily { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState Databases { get { throw null; } set { } }
        public virtual string DefaultEncoding { get { throw null; } set { } }
        public virtual int DefaultFixedFontSize { get { throw null; } set { } }
        public virtual int DefaultFontSize { get { throw null; } set { } }
        public virtual string FantasyFontFamily { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState FileAccessFromFileUrls { get { throw null; } set { } }
        public virtual string FixedFontFamily { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState ImageLoading { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState ImageShrinkStandaloneToFit { get { throw null; } set { } }
        public virtual bool IsDisposed { get { throw null; } }
        public virtual Fluxonaut.Browser.CefState Javascript { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState JavascriptAccessClipboard { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState JavascriptCloseWindows { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState JavascriptDomPaste { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState LocalStorage { get { throw null; } set { } }
        public virtual int MinimumFontSize { get { throw null; } set { } }
        public virtual int MinimumLogicalFontSize { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState Plugins { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState RemoteFonts { get { throw null; } set { } }
        public virtual string SansSerifFontFamily { get { throw null; } set { } }
        public virtual string SerifFontFamily { get { throw null; } set { } }
        public virtual string StandardFontFamily { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState TabToLinks { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState TextAreaResize { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState UniversalAccessFromFileUrls { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState WebGl { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.CefState WebSecurity { get { throw null; } set { } }
        public virtual int WindowlessFrameRate { get { throw null; } set { } }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~BrowserSettings() { }
        public virtual Fluxonaut.Browser.IBrowserSettings UnWrap() { throw null; }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public sealed partial class Cef
    {
        public Cef() { }
        public static string CefCommitHash { get { throw null; } }
        public static string Fluxonaut.BrowserVersion { get { throw null; } }
        public static string CefVersion { get { throw null; } }
        public static string ChromiumVersion { get { throw null; } }
        public static bool CrashReportingEnabled { get { throw null; } }
        public static System.Threading.Tasks.TaskFactory FileThreadTaskFactory { get { throw null; } set { } }
        public static System.Threading.Tasks.TaskFactory IOThreadTaskFactory { get { throw null; } set { } }
        public static bool IsInitialized { get { throw null; } }
        public static System.Threading.Tasks.TaskFactory UIThreadTaskFactory { get { throw null; } set { } }
        public static bool AddCrossOriginWhitelistEntry(string sourceOrigin, string targetProtocol, string targetDomain, bool allowTargetSubdomains) { throw null; }
        public static void AddDisposable(System.IDisposable item) { }
        public static bool ClearCrossOriginWhitelist() { throw null; }
        public static bool ClearSchemeHandlerFactories() { throw null; }
        public static uint ColorSetARGB(uint a, uint r, uint g, uint b) { throw null; }
        public static bool CurrentlyOnThread(Fluxonaut.Browser.CefThreadIds threadId) { throw null; }
        public static void DoMessageLoopWork() { }
        public static void EnableHighDPISupport() { }
        public static void EnableWaitForBrowsersToClose() { }
        public static int ExecuteProcess() { throw null; }
        public static Fluxonaut.Browser.ICookieManager GetGlobalCookieManager() { throw null; }
        public static Fluxonaut.Browser.ICookieManager GetGlobalCookieManager(Fluxonaut.Browser.ICompletionCallback callback) { throw null; }
        public static Fluxonaut.Browser.IRequestContext GetGlobalRequestContext() { throw null; }
        public static string GetMimeType(string extension) { throw null; }
        public static System.Threading.Tasks.Task<System.Collections.Generic.List<Fluxonaut.Browser.WebPluginInfo>> GetPlugins() { throw null; }
        public static bool Initialize(Fluxonaut.Browser.Core.CefSettingsBase cefSettings) { throw null; }
        public static bool Initialize(Fluxonaut.Browser.Core.CefSettingsBase cefSettings, bool performDependencyCheck) { throw null; }
        public static bool Initialize(Fluxonaut.Browser.Core.CefSettingsBase cefSettings, bool performDependencyCheck, Fluxonaut.Browser.IApp cefApp) { throw null; }
        public static bool Initialize(Fluxonaut.Browser.Core.CefSettingsBase cefSettings, bool performDependencyCheck, Fluxonaut.Browser.IBrowserProcessHandler browserProcessHandler) { throw null; }
        public static void PreShutdown() { }
        public static void QuitMessageLoop() { }
        public static void RefreshWebPlugins() { }
        public static void RegisterWidevineCdm(string path, Fluxonaut.Browser.IRegisterCdmCallback callback) { }
        public static System.Threading.Tasks.Task<Fluxonaut.Browser.CdmRegistration> RegisterWidevineCdmAsync(string path) { throw null; }
        public static bool RemoveCrossOriginWhitelistEntry(string sourceOrigin, string targetProtocol, string targetDomain, bool allowTargetSubdomains) { throw null; }
        public static void RemoveDisposable(System.IDisposable item) { }
        public static void RunMessageLoop() { }
        public static void SetCrashKeyValue(string key, string value) { }
        public static void Shutdown() { }
        public static void ShutdownWithoutChecks() { }
        public static void UnregisterInternalWebPlugin(string path) { }
        public static void VisitWebPluginInfo(Fluxonaut.Browser.IWebPluginInfoVisitor visitor) { }
        public static void WaitForBrowsersToClose() { }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public abstract partial class CefSettingsBase : System.IDisposable
    {
        public CefSettingsBase() { }
        public string AcceptLanguageList { get { throw null; } set { } }
        public string ApplicationClientIdForFileScanning { get { throw null; } set { } }
        public uint BackgroundColor { get { throw null; } set { } }
        public string BrowserSubprocessPath { get { throw null; } set { } }
        public string CachePath { get { throw null; } set { } }
        public Fluxonaut.Browser.Internals.CommandLineArgDictionary CefCommandLineArgs { get { throw null; } }
        public System.Collections.Generic.IEnumerable<Fluxonaut.Browser.CefCustomScheme> CefCustomSchemes { get { throw null; } }
        public bool CommandLineArgsDisabled { get { throw null; } set { } }
        public bool ExternalMessagePump { get { throw null; } set { } }
        public bool IgnoreCertificateErrors { get { throw null; } set { } }
        public string JavascriptFlags { get { throw null; } set { } }
        public string Locale { get { throw null; } set { } }
        public string LocalesDirPath { get { throw null; } set { } }
        public string LogFile { get { throw null; } set { } }
        public Fluxonaut.Browser.LogSeverity LogSeverity { get { throw null; } set { } }
        public bool MultiThreadedMessageLoop { get { throw null; } set { } }
        public bool PackLoadingDisabled { get { throw null; } set { } }
        public bool PersistSessionCookies { get { throw null; } set { } }
        public bool PersistUserPreferences { get { throw null; } set { } }
        public string ProductVersion { get { throw null; } set { } }
        public int RemoteDebuggingPort { get { throw null; } set { } }
        public string ResourcesDirPath { get { throw null; } set { } }
        public string RootCachePath { get { throw null; } set { } }
        public int UncaughtExceptionStackSize { get { throw null; } set { } }
        public string UserAgent { get { throw null; } set { } }
        public string UserDataPath { get { throw null; } set { } }
        public bool WindowlessRenderingEnabled { get { throw null; } set { } }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~CefSettingsBase() { }
        public void RegisterScheme(Fluxonaut.Browser.CefCustomScheme cefCustomScheme) { }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class DragData : Fluxonaut.Browser.Internals.CefWrapper, Fluxonaut.Browser.IDragData
    {
        internal DragData() { }
        public virtual string FileName { get { throw null; } set { } }
        public virtual System.Collections.Generic.IList<string> FileNames { get { throw null; } }
        public virtual string FragmentBaseUrl { get { throw null; } set { } }
        public virtual string FragmentHtml { get { throw null; } set { } }
        public virtual string FragmentText { get { throw null; } set { } }
        public virtual bool HasImage { get { throw null; } }
        public virtual Fluxonaut.Browser.IImage Image { get { throw null; } }
        public virtual Fluxonaut.Browser.Structs.Point ImageHotspot { get { throw null; } }
        public virtual bool IsFile { get { throw null; } set { } }
        public virtual bool IsFragment { get { throw null; } set { } }
        public virtual bool IsLink { get { throw null; } set { } }
        public virtual bool IsReadOnly { get { throw null; } set { } }
        public virtual string LinkMetaData { get { throw null; } set { } }
        public virtual string LinkTitle { get { throw null; } set { } }
        public virtual string LinkUrl { get { throw null; } set { } }
        public virtual void AddFile(string path, string displayName) { }
        public virtual Fluxonaut.Browser.IDragData Clone() { throw null; }
        public static Fluxonaut.Browser.IDragData Create() { throw null; }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~DragData() { }
        public virtual long GetFileContents(System.IO.Stream stream) { throw null; }
        public virtual void ResetFileContents() { }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class ManagedCefBrowserAdapter : Fluxonaut.Browser.Internals.IBrowserAdapter
    {
        public ManagedCefBrowserAdapter(Fluxonaut.Browser.Internals.IWebBrowserInternal webBrowserInternal, bool offScreenRendering) { }
        public virtual bool IsDisposed { get { throw null; } }
        public virtual Fluxonaut.Browser.Internals.IJavascriptCallbackFactory JavascriptCallbackFactory { get { throw null; } }
        public virtual Fluxonaut.Browser.Internals.IJavascriptObjectRepositoryInternal JavascriptObjectRepository { get { throw null; } }
        public virtual Fluxonaut.Browser.Internals.IMethodRunnerQueue MethodRunnerQueue { get { throw null; } }
        public virtual void CreateBrowser(Fluxonaut.Browser.IWindowInfo windowInfo, Fluxonaut.Browser.IBrowserSettings browserSettings, Fluxonaut.Browser.IRequestContext requestContext, string address) { }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~ManagedCefBrowserAdapter() { }
        public virtual Fluxonaut.Browser.IBrowser GetBrowser(int browserId) { throw null; }
        public virtual void OnAfterBrowserCreated(Fluxonaut.Browser.IBrowser browser) { }
        public virtual void Resize(int width, int height) { }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public sealed partial class NativeMethodWrapper
    {
        public NativeMethodWrapper() { }
        public static bool IsFocused(System.IntPtr handle) { throw null; }
        public static void MemoryCopy(System.IntPtr dest, System.IntPtr src, int numberOfBytes) { }
        public static void RemoveExNoActivateStyle(System.IntPtr browserHwnd) { }
        public static void SetWindowParent(System.IntPtr child, System.IntPtr newParent) { }
        public static void SetWindowPosition(System.IntPtr handle, int x, int y, int width, int height) { }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class PopupFeatures : Fluxonaut.Browser.IPopupFeatures, System.IDisposable
    {
        internal PopupFeatures() { }
        public virtual int? Height { get { throw null; } }
        public virtual bool MenuBarVisible { get { throw null; } }
        public virtual bool ScrollbarsVisible { get { throw null; } }
        public virtual bool StatusBarVisible { get { throw null; } }
        public virtual bool ToolBarVisible { get { throw null; } }
        public virtual int? Width { get { throw null; } }
        public virtual int? X { get { throw null; } }
        public virtual int? Y { get { throw null; } }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~PopupFeatures() { }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class PostData : Fluxonaut.Browser.Internals.CefWrapper, Fluxonaut.Browser.IPostData
    {
        public PostData() { }
        public virtual System.Collections.Generic.IList<Fluxonaut.Browser.IPostDataElement> Elements { get { throw null; } }
        public virtual bool HasExcludedElements { get { throw null; } }
        public virtual bool IsReadOnly { get { throw null; } }
        public virtual bool AddElement(Fluxonaut.Browser.IPostDataElement element) { throw null; }
        public virtual Fluxonaut.Browser.IPostDataElement CreatePostDataElement() { throw null; }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~PostData() { }
        public virtual bool RemoveElement(Fluxonaut.Browser.IPostDataElement element) { throw null; }
        public virtual void RemoveElements() { }
        public virtual Fluxonaut.Browser.IPostData UnWrap() { throw null; }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class PostDataElement : Fluxonaut.Browser.Internals.CefWrapper, Fluxonaut.Browser.IPostDataElement
    {
        public PostDataElement() { }
        public virtual byte[] Bytes { get { throw null; } set { } }
        public virtual string File { get { throw null; } set { } }
        public virtual bool IsReadOnly { get { throw null; } }
        public virtual Fluxonaut.Browser.PostDataElementType Type { get { throw null; } }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~PostDataElement() { }
        public virtual void SetToEmpty() { }
        public virtual Fluxonaut.Browser.IPostDataElement UnWrap() { throw null; }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class Request : Fluxonaut.Browser.Internals.CefWrapper, Fluxonaut.Browser.IRequest
    {
        public Request() { }
        public virtual Fluxonaut.Browser.UrlRequestFlags Flags { get { throw null; } set { } }
        public virtual System.Collections.Specialized.NameValueCollection Headers { get { throw null; } set { } }
        public virtual ulong Identifier { get { throw null; } }
        public virtual bool IsReadOnly { get { throw null; } }
        public virtual string Method { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.IPostData PostData { get { throw null; } set { } }
        public virtual Fluxonaut.Browser.ReferrerPolicy ReferrerPolicy { get { throw null; } }
        public virtual string ReferrerUrl { get { throw null; } }
        public virtual Fluxonaut.Browser.ResourceType ResourceType { get { throw null; } }
        public virtual Fluxonaut.Browser.TransitionType TransitionType { get { throw null; } }
        public virtual string Url { get { throw null; } set { } }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~Request() { }
        public virtual string GetHeaderByName(string name) { throw null; }
        public virtual void InitializePostData() { }
        public virtual void SetHeaderByName(string name, string value, bool overwrite) { }
        public virtual void SetReferrer(string referrerUrl, Fluxonaut.Browser.ReferrerPolicy policy) { }
        public virtual Fluxonaut.Browser.IRequest UnWrap() { throw null; }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class RequestContext : Fluxonaut.Browser.Internals.CefWrapper, Fluxonaut.Browser.IRequestContext
    {
        public RequestContext() { }
        public RequestContext(Fluxonaut.Browser.Core.RequestContextSettings settings) { }
        public RequestContext(Fluxonaut.Browser.Core.RequestContextSettings settings, Fluxonaut.Browser.IRequestContextHandler requestContextHandler) { }
        public RequestContext(Fluxonaut.Browser.IRequestContext otherRequestContext) { }
        public RequestContext(Fluxonaut.Browser.IRequestContext otherRequestContext, Fluxonaut.Browser.IRequestContextHandler requestContextHandler) { }
        public RequestContext(Fluxonaut.Browser.IRequestContextHandler requestContextHandler) { }
        public virtual string CachePath { get { throw null; } }
        public virtual bool IsGlobal { get { throw null; } }
        public virtual bool CanSetPreference(string name) { throw null; }
        public virtual void ClearCertificateExceptions(Fluxonaut.Browser.ICompletionCallback callback) { }
        public virtual void ClearHttpAuthCredentials(Fluxonaut.Browser.ICompletionCallback callback) { }
        public virtual bool ClearSchemeHandlerFactories() { throw null; }
        public virtual void CloseAllConnections(Fluxonaut.Browser.ICompletionCallback callback) { }
        public static Fluxonaut.Browser.IRequestContext CreateContext(Fluxonaut.Browser.IRequestContext other, Fluxonaut.Browser.IRequestContextHandler requestContextHandler) { throw null; }
        public virtual bool DidLoadExtension(string extensionId) { throw null; }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~RequestContext() { }
        public virtual System.Collections.Generic.IDictionary<string, object> GetAllPreferences(bool includeDefaults) { throw null; }
        public virtual Fluxonaut.Browser.ICookieManager GetCookieManager(Fluxonaut.Browser.ICompletionCallback callback) { throw null; }
        public virtual Fluxonaut.Browser.IExtension GetExtension(string extensionId) { throw null; }
        public virtual bool GetExtensions(out System.Collections.Generic.IList<string> extensionIds) { throw null; }
        public virtual object GetPreference(string name) { throw null; }
        public virtual bool HasExtension(string extensionId) { throw null; }
        public virtual bool HasPreference(string name) { throw null; }
        public virtual bool IsSame(Fluxonaut.Browser.IRequestContext context) { throw null; }
        public virtual bool IsSharingWith(Fluxonaut.Browser.IRequestContext context) { throw null; }
        public virtual void LoadExtension(string rootDirectory, string manifestJson, Fluxonaut.Browser.IExtensionHandler handler) { }
        public virtual void PurgePluginListCache(bool reloadPages) { }
        public virtual bool RegisterSchemeHandlerFactory(string schemeName, string domainName, Fluxonaut.Browser.ISchemeHandlerFactory factory) { throw null; }
        public virtual System.Threading.Tasks.Task<Fluxonaut.Browser.ResolveCallbackResult> ResolveHostAsync(System.Uri origin) { throw null; }
        public virtual bool SetPreference(string name, object value, out string error) { throw null; }
        public virtual Fluxonaut.Browser.IRequestContext UnWrap() { throw null; }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class RequestContextSettings : System.IDisposable
    {
        public RequestContextSettings() { }
        public string AcceptLanguageList { get { throw null; } set { } }
        public string CachePath { get { throw null; } set { } }
        public bool IgnoreCertificateErrors { get { throw null; } set { } }
        public bool PersistSessionCookies { get { throw null; } set { } }
        public bool PersistUserPreferences { get { throw null; } set { } }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~RequestContextSettings() { }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class UrlRequest : Fluxonaut.Browser.Internals.CefWrapper, Fluxonaut.Browser.IUrlRequest
    {
        public UrlRequest(Fluxonaut.Browser.IRequest request, Fluxonaut.Browser.IUrlRequestClient urlRequestClient) { }
        public UrlRequest(Fluxonaut.Browser.IRequest request, Fluxonaut.Browser.IUrlRequestClient urlRequestClient, Fluxonaut.Browser.IRequestContext requestContext) { }
        public virtual Fluxonaut.Browser.UrlRequestStatus RequestStatus { get { throw null; } }
        public virtual Fluxonaut.Browser.IResponse Response { get { throw null; } }
        public virtual bool ResponseWasCached { get { throw null; } }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~UrlRequest() { }
    }
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    public partial class WindowInfo : Fluxonaut.Browser.IWindowInfo
    {
        public WindowInfo() { }
        public virtual uint ExStyle { get { throw null; } set { } }
        public virtual bool ExternalBeginFrameEnabled { get { throw null; } set { } }
        public virtual int Height { get { throw null; } set { } }
        public virtual System.IntPtr ParentWindowHandle { get { throw null; } set { } }
        public virtual bool SharedTextureEnabled { get { throw null; } set { } }
        public virtual uint Style { get { throw null; } set { } }
        public virtual int Width { get { throw null; } set { } }
        public virtual System.IntPtr WindowHandle { get { throw null; } set { } }
        public virtual bool WindowlessRenderingEnabled { get { throw null; } set { } }
        public virtual int X { get { throw null; } set { } }
        public virtual int Y { get { throw null; } set { } }
        public void Dispose() { }
        protected virtual void Dispose(bool A_0) { }
        ~WindowInfo() { }
        public virtual void SetAsChild(System.IntPtr parentHandle) { }
        public virtual void SetAsChild(System.IntPtr parentHandle, int left, int top, int right, int bottom) { }
        public virtual void SetAsPopup(System.IntPtr parentHandle, string windowName) { }
        public virtual void SetAsWindowless(System.IntPtr parentHandle) { }
        public virtual Fluxonaut.Browser.IWindowInfo UnWrap() { throw null; }
    }
}
namespace Fluxonaut.Browser.Internals
{
    public abstract partial class CefWrapper
    {
        internal CefWrapper() { }
        protected bool _disposed;
        public virtual bool IsDisposed { get { throw null; } }
        protected void ThrowIfDisposed() { }
        protected void ThrowIfExecutedOnNonCefUiThread() { }
    }
}
